### ISSUE TITLE
2 22 answer backwards?

### ISSUE THREAD

**Issue by R82913** [flackr/crosswordle#27]
Phone and screen clues are on opposite words

**Comment by flackr** [comment]
I'm not sure I follow, can you clarify which was the horizontal and which was the vertical word? The horizontal word is always the "first" word - you can see this from which of the two words is listed first in the previous guesses. For me, it looks correct.

**Comment by R82913** [comment]
Thanks Robert, this was my friend Robins first try and you can see the R
was greyed out but then was in the final word. Maybe we are doing it wrong?
Thanks again!
Johanna

**Comment by flackr** [comment]
I think you may have tried to include a picture, but it seems to have been lost.

I suspect that your friend Robin had an R in both words, and was confused when the one in the horizontal word turned yellow but not the one in the vertical word? If so this is because currently the "first" occurrence of the letter (where the horizontal word comes first) will be the one to turn yellow. The second R would be grayed out because there are no more R's in the final answer. Can you confirm if this is the case?

If so, the proposed update in issue #11 where it will match yellow letters in the same word first will make things easier.

**Comment by R82913** [comment]
Ok I'll try again. Thanks so much for your prompt attention!!

**Comment by channeled28** [comment]
![7D91F267-F979-4964-92F7-DFFB8D991301](https://user-images.githubusercontent.com/100330203/155450207-1389ec99-b822-4c33-9902-f5f1ed24280a.png)

The issue is that if I put an “i” in both words, they both turn yellow, even though there is only one “i” total in the answer. If they both turn yellow it implies there are two in the answer

**Comment by R82913** [comment]
Why can't you run the two words independently with one set of results being
exclusive to the five letter word and the other exclusive to the six letter
word. That is what we intuitively expected.

**Comment by flackr** [comment]
Treating it as two separate wordles is certainly a possibility, however I feel like getting clues about the overall puzzle is one of the things that makes this an interesting and unique variation on wordle. There are plenty of other games which do this, e.g. https://zaratustra.itch.io/dordle, https://www.quordle.com/, https://crosswordle.xyz/. I'd also be worried about changing the game so dramatically when people are used to it working as a global puzzle. I added an underline to the shared letter to indicate it represents the same clue though I'm happy to do whatever else I can to make it more clear (e.g. I could draw the second copy of the letter without any color).

**Comment by R82913** [comment]
Ok thanks! I'm getting used to it!🙂👍

**Comment by flackr** [comment]
Great! Glad to hear it!
