### ISSUE TITLE
More instructions about the keyboard coloring

### ISSUE THREAD

**Issue by GrandizerGo** [flackr/crosswordle#31]
I thought that since the color grey was used for letters not in the word, that if a letter was grey in the Letter Board, it was also not used. In fact todays puzzle shows how wrong this is. Whipped Cream showed in the letter board that E, C and R were all grey.
I also did not know until today that the letter board shows a white letter even if the letter is in the perfect place, I found it is a hint that there is more then one of these letters in the puzzle.
More instructions on the Letter Board are SORELY NEEDED.

**Comment by flackr** [comment]
Can you clarify what you mean by the letter board? Is this the keyboard?

If so, the keyboard tracks how many of a letter could be in the word based on the clues you have been given, e.g. if you guessed a word with a single E, and it was yellow or green, you know that there is one E in the answer but there may be more. On the other hand if your guess had two E's and only one of them was green / yellow there can only possibly be one E in the answer. As a result once you've typed on E the E turns dark to indicate there can be no more.

I can add a section to the help instructions to explain this when I find time.

**Comment by GrandizerGo** [comment]
Yes, sorry it was the keyboard I was referring to.
I have not really looked at it any more since this comment, I play daily still though. It just seems weird that the keyboard would show that a letter was not used when in fact it was used. I have not looked at any changes to the options, I did notice that for a few days, there were hatch marks going through some letters, and there was a notice that things were changed a bit, however after a week? it seemed to return to normal. I did not like those hatch markings and the letters were no longer properly centered in the boxes.

**Comment by flackr** [comment]
I'm still not sure what you mean that it shows a letter was not used when it was? Are you referring to how it changes from green/yellow to grey after the letter is used in your guess?

**Comment by GrandizerGo** [comment]
In the example I used, the puzzle was whipped cream, the keyboard showed grey letters for the W, the C and the E,  I thought grey was meant for letters NOT In the puzzle, yet in this case all three letters are in fact in the puzzle.

**Comment by flackr** [comment]
Right, so I'm guessing W, C, and E were already in your current guess though (maybe auto-filled because they were green), so the keyboard was telling you that there may or may not be more of them, just as there may or may not be any other letter you haven't tried yet. I added this to make it easier when you're coming up with guesses to know what letters you may still need. They shouldn't have turned dark gray though unless you had a clue to indicate there could not be more of them.

Thanks for explaining, I'll add a description of how the keyboard updates based on what you've typed so far to the help page to try to make this more clear.

**Comment by GrandizerGo** [comment]
Thank you.
