### ISSUE TITLE
One of today's words longer than maximum length

### ISSUE THREAD

**Issue by Oleenick** [flackr/crosswordle#37]
Hi, 

Just noticed that one of today's words is 12 letters long. After looking through the code availible here I found the max length was set to 10, with this being the only word on the list that is above 12 letters. I successfully decoded the other word of today from the puzzles array which is 7 letters. However, with the same decoding function I'm unable to decode this 12 letter word, maybe it was encoded incorrectly given a filter of maximum 10 characters?

Any ideas?

Thanks.

**Comment by wordlover111** [comment]
There’s definitely something wrong with today’s Crosswordle. Every 12 letter word I put in did not work.

**Comment by JessFrancesB** [comment]
> Hi,
> 
> Just noticed that one of today's words is 12 letters long. After looking through the code availible here I found the max length was set to 10, with this being the only word on the list that is above 12 letters. I successfully decoded the other word of today from the puzzles array which is 7 letters. However, with the same decoding function I'm unable to decode this 12 letter word, maybe it was encoded incorrectly given a filter of maximum 10 characters?
> 
> Any ideas?
> 
> Thanks.

I'm guessing what happened was that whoever submitted the puzzle wasn't aware of this and accidentally made it unsolvable for all of us. Maybe it should be made clear when submitting that there's a maximum of 10 letters, or something should be added to prevent submitting words over 10 letters. I'm really frustrated and I hope that we can at least be told the answer if it doesn't get fixed in time.

**Comment by keldonwordle** [comment]
Yes, it’s definitely glitched as I tried “complication” and it says it’s not a word along with every other 12 letter word. Please fix I love this game :) @flackr

**Comment by flackr** [comment]
Thanks for the bug reports. Apologies for the broken puzzle. I have a script I've been using to add the words which somehow missed that today's was longer than my current dictionary length. I've increased the limit though you'll have to force reload to get the new code right away as otherwise your browser will load the game from cache.

**Comment by wordlover111** [comment]
It’s all good! Thank you so much for all you do! I appreciate it and you, Robert! From a fellow word lover! 🙂Ann Lindgren CattSent from my iPadOn Jan 18, 2024, at 10:09 AM, Robert Flack ***@***.***> wrote:﻿
Thanks for the bug reports. Apologies for the broken puzzle. I have a script I've been using to add the words which somehow missed that today's was longer than my current dictionary length. I've increased the limit though you'll have to force reload to get the new code right away as otherwise your browser will load the game from cache.
